### ISSUE TITLE
Exception if not first_time run but no previous post available

### ISSUE THREAD

**Issue by nemobis** [robertoszek/pleroma-bot#41]
Thank you for this bot, I love how easy it is to configure!

I interrupted the first run, so I had no posts on the target mastodon account, and upon the second try I got:
```
Traceback (most recent call last):
  File "/home/federico/git/federico/mastodon/lib64/python3.9/site-packages/pleroma_bot/cli.py", line 378, in main
    date_pleroma = user.get_date_last_pleroma_post()
  File "/home/federico/git/federico/mastodon/lib64/python3.9/site-packages/pleroma_bot/_pleroma.py", line 35, in get_date_last_pleroma_post
    response.raise_for_status()
  File "/home/federico/git/federico/mastodon/lib64/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mastodon.technology//api/v1/accounts/<username>/statuses
```
I could easy work around this by using `--forceDate`, which is mentioned in https://robertoszek.github.io/pleroma-bot/gettingstarted/usage/#first-run , so no big deal, but maybe the date should fall back to the default?

**Comment by nemobis** [comment]
Actually this happens even when using force date and having previous posts:
```
✖ 2021-04-28 09:23:49,686 - pleroma_bot - ERROR - Exception occurred (cli.py:432) 
Traceback (most recent call last):
  File "/home/federico/git/federico/mastodon/lib64/python3.9/site-packages/pleroma_bot/cli.py", line 420, in main
    user.check_pinned()
  File "/home/federico/git/federico/mastodon/lib64/python3.9/site-packages/pleroma_bot/_utils.py", line 137, in check_pinned
    pleroma_pinned_post = self.pin_pleroma(id_post_to_pin)
  File "/home/federico/git/federico/mastodon/lib64/python3.9/site-packages/pleroma_bot/_pin.py", line 21, in pin_pleroma
    self.unpin_pleroma(pinned_file)
  File "/home/federico/git/federico/mastodon/lib64/python3.9/site-packages/pleroma_bot/_pin.py", line 64, in unpin_pleroma
    _find_pinned(self, pinned_file)
  File "/home/federico/git/federico/mastodon/lib64/python3.9/site-packages/pleroma_bot/_pin.py", line 95, in _find_pinned
    response.raise_for_status()
  File "/home/federico/git/federico/mastodon/lib64/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mastodon.technology/api/v1/accounts/RelexSolutions/statuses
```

**Comment by robertoszek** [comment]
Hi!
Thanks for the kind words!

That's a edge-case I overlook when trying to guess if this is the first run for that user, I think.
I assume that the user directory was created during the first run (while it started to gather the tweets) but none were posted to the Fediverse instance, right?
Do you recall when did you interrupt the run? It'd be very helpful to reproduce the issue on my side.

**Comment by nemobis** [comment]
Il 28/04/21 21:02, robertoszek ha scritto:
> Do you recall when did you interrupt the run? It'd be very helpful to reproduce the issue on my side.

I think at some point during "gathering tweets". I have a patch to 
handle some exceptions (nothing particularly smart), I'll try to send it 
later this week.

**Comment by nemobis** [comment]
But I noticed that https://docs.joinmastodon.org/methods/statuses/ says 
that in a GET call to

 > https://mastodon.example/api/v1/statuses/:id

the ":id" is a required parameter. I got lost checking in the Mastodon 
code whether there are workarounds or whether this was ever different.

**Comment by robertoszek** [comment]
The endpoint here actually is:
`https://mastodon.example/api/v1/accounts/:id/statuses`

Where `:id` is the account ID, and yes, it is required.
See here, for example:
https://mastodon.technology/api/v1/accounts/137249/statuses

We use this particular endpoint because it's interoperable with Pleroma's API:
https://docs.pleroma.social/backend/development/API/differences_in_mastoapi_responses/#accounts

**Comment by robertoszek** [comment]
I also included a mention of it on the documentation, so it's clear you need the account ID instead of the username when using Mastodon.
https://robertoszek.github.io/pleroma-bot/gettingstarted/configuration/#mastodon

**Comment by robertoszek** [comment]
@nemobis did you manage to get it working?
I was not able to reproduce it, so I will end up closing this issue eventually due to inactivity if it does not happen on the latest version.

**Comment by nemobis** [comment]
Il 05/12/21 09:03, robertoszek ha scritto:
> @nemobis did you manage to get it working?

Yes it's working for me now (although I don't remember what I changed to 
make it work), so I've not looked into it any more. I'll close the issue 
and I can reopen if it happens again and I have more precise information.

Thank you for the reminder!

**Comment by robertoszek** [comment]
No problem! Thanks for the reply, as you said, feel free to reopen it if you encounter it again.
Have a nice day!
