### ISSUE TITLE
Exception in user.check_pinned() for Mastodon 3.3: 404 Client Error: Not Found

### ISSUE THREAD

**Issue by nemobis** [robertoszek/pleroma-bot#43]
```
ℹ 2021-04-28 09:23:07,426 - pleroma_bot - INFO - (6/6) 
ℹ 2021-04-28 09:23:08,119 - pleroma_bot - INFO - Post in Pleroma:       <Response [200]> 
ℹ 2021-04-28 09:23:48,160 - pleroma_bot - INFO - Current pinned:        1385197439225896962 
ℹ 2021-04-28 09:23:48,161 - pleroma_bot - INFO - Previous pinned:       None 
ℹ 2021-04-28 09:23:49,247 - pleroma_bot - INFO - Post in Pleroma:       <Response [200]> 
ℹ 2021-04-28 09:23:49,249 - pleroma_bot - INFO - File with previous pinned post ID not found or empty. Checking last posts for pinned post... 
✖ 2021-04-28 09:23:49,686 - pleroma_bot - ERROR - Exception occurred (cli.py:432) 
Traceback (most recent call last):
  File "/home/federico/git/federico/mastodon/lib64/python3.9/site-packages/pleroma_bot/cli.py", line 420, in main
    user.check_pinned()
  File "/home/federico/git/federico/mastodon/lib64/python3.9/site-packages/pleroma_bot/_utils.py", line 137, in check_pinned
    pleroma_pinned_post = self.pin_pleroma(id_post_to_pin)
  File "/home/federico/git/federico/mastodon/lib64/python3.9/site-packages/pleroma_bot/_pin.py", line 21, in pin_pleroma
    self.unpin_pleroma(pinned_file)
  File "/home/federico/git/federico/mastodon/lib64/python3.9/site-packages/pleroma_bot/_pin.py", line 64, in unpin_pleroma
    _find_pinned(self, pinned_file)
  File "/home/federico/git/federico/mastodon/lib64/python3.9/site-packages/pleroma_bot/_pin.py", line 95, in _find_pinned
    response.raise_for_status()
  File "/home/federico/git/federico/mastodon/lib64/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mastodon.technology/api/v1/accounts/RelexSolutions/statuses

**Comment by robertoszek** [comment]
Hi!
Is this happening always for the `/statuses` endpoint?
For Mastodon instances I'm pretty sure you have to set the account ID in the `pleroma_username` config mapping:
```
- twitter_username: WoolieWoolz
  pleroma_username: 24660
  pleroma_base_url: https://botsin.space
  [...]
```
The ease of finding the ID for your Mastodon account varies between instances, maybe you can try this proposed solution:
https://discourse.joinmastodon.org/t/how-to-get-mastodons-user-id-from-mastodon-account-acct-username-server/1658/8

Let me know if it still fails using the account ID.

**Comment by nemobis** [comment]
Uh! Silly me, I had put the username instead of the user ID in the `pleroma_username` variable, not understanding why the example had an integer there. :) Posting statuses worked but everything else didn't. Thank you!
