### ISSUE TITLE
Handle HTTP 429 from Twitter API

### ISSUE THREAD

**Issue by nemobis** [robertoszek/pleroma-bot#72]
When pleroma-bot cycles through profiles very quickly (for lack of tweets to post), it always tries to update the profiles. The Twitter API request to get the pinned tweet was the first to get an HTTP 429. It would be nice to sleep a bit before continuing with the next user, which otherwise will also fail.
```
ℹ 2022-04-04 09:00:50,264 - pleroma_bot - INFO - Processing user:       108071095671376766
ℹ 2022-04-04 09:00:50,264 - pleroma_bot - INFO - It seems like pleroma-bot is running for the first time for this Twitter user: ZovkoEU
✖ 2022-04-04 09:00:50,491 - pleroma_bot - ERROR - Exception occurred for user, skipping... (cli.py:554) 
Traceback (most recent call last):                                                        
  File "/home/7/federico/mastodon/lib/python3.7/site-packages/pleroma_bot/cli.py", line 435, in main
    user = User(user_item, config, base_path)                                              
  File "/home/7/federico/mastodon/lib/python3.7/site-packages/pleroma_bot/cli.py", line 199, in __init__                 
    self.pinned_tweet_id = self._get_pinned_tweet_id()                                              
  File "/home/7/federico/mastodon/lib/python3.7/site-packages/pleroma_bot/_pin.py", line 252, in _get_pinned_tweet_id
    response.raise_for_status()                                                                     
  File "/home/7/federico/mastodon/lib/python3.7/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)                                                                   
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.twitter.com/2/users/by/username/ZovkoEU?user.fields=pinned_tweet_id&expansions=pinned_tweet_id&tweet.fields=entities
```

**Comment by robertoszek** [comment]
Agreed, code 429 should be handled. 
Rate limits in general, 
https://developer.twitter.com/en/docs/twitter-api/rate-limits

Looking at the header `x-rate-limit-reset:` should be simple enough to check when a new request could be sent, instead of sleeping for an arbitrary amount of time.

**Comment by robertoszek** [comment]
I've implemented some basic handling for Twitter rate limits in `1.0.3rc10`:
```
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pleroma-bot==1.0.3rc10
```
Feel free to try it out and see if you find any issues still.

**Comment by nemobis** [comment]
Thanks! I'm also getting [rate limited by Mastodon](https://docs.joinmastodon.org/api/rate-limits/) btw. :innocent: 

```
Traceback (most recent call last):                                                                                                                                                                                                          
  File "/home/federico/mw/pleroma-bot/res/lib64/python3.10/site-packages/pleroma_bot/_pleroma.py", line 103, in post_pleroma                                                                                                                
    response.raise_for_status()                                                                                       
  File "/home/federico/mw/pleroma-bot/res/lib64/python3.10/site-packages/requests/models.py", line 960, in raise_for_status                                                                                                                 
    raise HTTPError(http_error_msg, response=self)                                                                    
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://respublicae.eu/api/v1/media                                                                                                                             
                                                                                                                      
During handling of the above exception, another exception occurred:                                                                                                                                                                         
                                                                                                                                                                                                                                            
Traceback (most recent call last):                                                                                    
  File "/home/federico/mw/pleroma-bot/res/lib64/python3.10/site-packages/pleroma_bot/cli.py", line 533, in main       
    post_id = user.post(                                                                                                                                                                                                                    
  File "/home/federico/mw/pleroma-bot/res/lib64/python3.10/site-packages/pleroma_bot/_utils.py", line 604, in post    
    post_id = self.post_pleroma(tweet, poll, sensitive)                                                               
  File "/home/federico/mw/pleroma-bot/res/lib64/python3.10/site-packages/pleroma_bot/_pleroma.py", line 130, in post_pleroma                                                                                                                
    response.raise_for_status()                                                                                       
  File "/home/federico/mw/pleroma-bot/res/lib64/python3.10/site-packages/requests/models.py", line 960, in raise_for_status                                                                                                                 
    raise HTTPError(http_error_msg, response=self)                                                                                                                                                                                          
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://respublicae.eu/api/v1/media   
```

**Comment by robertoszek** [comment]
Hahaha

Yeah, that's a problem I intended to look into for all 3 supported types of instances (Pleroma, Mastodon, Misskey) but I didn't get around to it yet.
I'll open a new separate issue to keep track of those, if you don't mind

**Comment by nemobis** [comment]
This is working fine for me, I think it can be closed. Thanks!
```
ℹ 2022-04-10 09:46:58,205 - pleroma_bot - INFO - Processing user:       108070113362316009 
ℹ 2022-04-10 09:46:58,439 - pleroma_bot - INFO - Rate limit exceeded. 0 out of 300 requests remaining until 2022-04-10 06:56:06 UTC 
ℹ 2022-04-10 09:46:58,439 - pleroma_bot - INFO - Sleeping for 550s...
```

**Comment by robertoszek** [comment]
Perfect! I'll close this once the changes are merged into the stable main branch and packaged into an official release then.
Thanks for your input!
